"""empty message

Revision ID: 78a87eb676e3
Revises: f3d0b6e8ffde
Create Date: 2023-12-29 19:42:53.656614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a87eb676e3'
down_revision = 'f3d0b6e8ffde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authorized', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_column('is_authorized')

    # ### end Alembic commands ###
