"""empty message

Revision ID: a38d5bccda30
Revises: c8502285eefd
Create Date: 2023-12-29 02:54:57.343721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38d5bccda30'
down_revision = 'c8502285eefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_two', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('certificate_three', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('certificate_four', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('certificate_five', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_column('certificate_five')
        batch_op.drop_column('certificate_four')
        batch_op.drop_column('certificate_three')
        batch_op.drop_column('certificate_two')

    # ### end Alembic commands ###
