"""empty message

Revision ID: c8502285eefd
Revises: 
Create Date: 2023-12-27 17:06:32.362021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8502285eefd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('country_origin', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('specialist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_physiotherapist', sa.Boolean(), nullable=False),
    sa.Column('is_nurse', sa.Boolean(), nullable=False),
    sa.Column('certificate', sa.String(length=400), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('img', sa.String(length=400), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('country_origin', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialist')
    op.drop_table('patient')
    # ### end Alembic commands ###
