"""empty message

Revision ID: f3d0b6e8ffde
Revises: a38d5bccda30
Create Date: 2023-12-29 15:24:08.171073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d0b6e8ffde'
down_revision = 'a38d5bccda30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=True),
    sa.Column('certificates_url', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_column('certificate_four')
        batch_op.drop_column('certificate_two')
        batch_op.drop_column('certificate_five')
        batch_op.drop_column('certificate')
        batch_op.drop_column('certificate_three')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_three', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certificate', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certificate_five', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certificate_two', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certificate_four', sa.VARCHAR(length=400), autoincrement=False, nullable=True))

    op.drop_table('certificates')
    # ### end Alembic commands ###
